name: Deploy Infrastructure and App

on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: "GKE machine type"
        required: true
        default: "e2-standard-2"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: online-boutique
  CLUSTER_ZONE: us-central1-a

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
        env:
          TF_VAR_machine_type: ${{ inputs.machine_type }}
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_machine_type: ${{ inputs.machine_type }}
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $CLUSTER_ZONE \
            --project $PROJECT_ID

      - name: Deploy manifests
        run: |
          kubectl apply -f ./release/kubernetes-manifests.yaml

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Create monitoring namespace
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Prometheus Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy monitoring stack
        run: |
          helm upgrade --install monitoring \
            prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            -f release/monitoring/values.yaml

      - name: Show service access
        run: |
          echo "Waiting for Grafana LoadBalancer IP..."
          
          while true; do
            EXTERNAL_IP=$(kubectl get svc monitoring-grafana -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [ -n "$EXTERNAL_IP" ]; then
              echo "Grafana available at: http://$EXTERNAL_IP"
              break
            fi

            echo "Still waiting..."
            sleep 30
          done

          echo ""
          echo "Waiting for frontend external IP..."

          while true; do
            FRONTEND_IP=$(kubectl get svc frontend-external -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [ -n "$FRONTEND_IP" ]; then
              echo "Frontend available at: http://$FRONTEND_IP"
              break
            fi

            echo "Still waiting for frontend..."
            sleep 10
          done
